### ISSUE TITLE
does it really need nim devel?

### ISSUE THREAD

**Issue by pietroppeter** [moigagoo/climate#1]
I wanted to try it out for a project but I am still on 1.6.x, does this project really needs 1.9.1 or it is just an accident of running `nimble init` while on devel? ;)

The idea is very nice btw, although there are quite a few libraries that help with building CLIs I think this is the only one that focuses on commands, which is very often just what I need! Thanks for this :)

**Comment by pietroppeter** [comment]
actually since source is so small I just copied and pasted in a local `climate.nim` and I can confirm it works also on 1.6.x :)

**Comment by moigagoo** [comment]
> actually since source is so small I just copied and pasted in a local climate.nim and I can confirm it works also on 1.6.x :)

Thanks! Do you mind sending a PR that fixes .nimble file?

**Comment by moigagoo** [comment]
Nevermind, updated the requirement.

**Comment by pietroppeter** [comment]
yep, sorry I could have made a PR myself but would not have know which version to target :) 1.6.2 is fine by me!
btw I am using it here https://github.com/pietroppeter/nblog/pull/16/ (will need to update the requires)

**Comment by moigagoo** [comment]
> btw I am using it here https://github.com/pietroppeter/nblog/pull/16 (will need to update the requires)

I am so happy you found Climate useful!

Please share your feature requests, I'll be happy to help.

I'll cut a new release today so that you could have a stable version in your requirements.
